In [1]:
# loading modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# loading dhe data
Brain = pd.read_csv("(only mammals) including whole brain data 13 07 2023 .csv")
# Brain = Brain.drop(['Unnamed: 0'], axis=1)
Brain.head(8)

Animal  Forebrain m  Cerebellum m  Whole brain m  \
0                        NaN          NaN           NaN            NaN   
1  African sheath-tailed bat       0.0899        0.0540          0.244   
2     Little free-tailed bat       0.0840        0.0360          0.208   
3         Rufous trident bat       0.0930        0.0720          0.251   
4       Common bent-wing bat       0.0858        0.0485          0.219   
5             Naked mole-rat       0.1840        0.0480          0.392   
6  Commerson's roundleaf bat       0.2430        0.1070          0.588   
7                Smoky shrew       0.0840        0.0200          0.176   

  Forebrain n Cerebellum n Whole brain n  Body m  
0         NaN          NaN           NaN     NaN  
1   5,080,000   47,984,000    58,580,000    11.5  
2   5,632,000   25,324,000    34,958,000     5.4  
3   6,039,000   59,651,000    69,763,000    13.7  
4   6,116,000   44,447,000    55,659,000    11.6  
5   6,150,000   15,740,000    26,880,000    35.3  
6   7,877,000   51,875,000    66,719,000   101.9  
7   9,730,000   20,870,000    36,460,000     7.5

In [3]:
# Dropping NaN values
Brain = Brain.dropna().reset_index(drop=True)

In [4]:
# Converting into float and removing commas
if Brain['Forebrain n'].dtype != 'float64':
     Brain['Forebrain n'] = Brain['Forebrain n'].str.replace(',', '').astype(float)
if Brain['Cerebellum n'].dtype != 'float64':
     Brain['Cerebellum n'] = Brain['Cerebellum n'].str.replace(',', '').astype(float)
if Brain['Whole brain n'].dtype != 'float64':
     Brain['Whole brain n'] = Brain['Whole brain n'].str.replace(',', '').astype(float)

In [5]:
# Getting relative cortical and cerebellar masses and relative number of neurons in each structure
Brain['Forebrain m r %'] = Brain['Forebrain m']/Brain['Whole brain m']*100
Brain['Cerebellum m r %'] = Brain['Cerebellum m']/Brain['Whole brain m']*100
Brain['Forebrain n r %'] = Brain['Forebrain n']/Brain['Whole brain n']*100
Brain['Cerebellum n r %'] = Brain['Cerebellum n']/Brain['Whole brain n']*100

In [9]:
# Getting neuron densities in a miligram of structure
Brain['Forebrain n d'] = Brain['Forebrain n']/(Brain['Forebrain m']*1000)
Brain['Cerebellum n d'] = Brain['Cerebellum n']/(Brain['Cerebellum m']*1000)
Brain['Whole brain n d'] = Brain['Whole brain n']/(Brain['Whole brain m']*1000)

In [12]:
# Number of neurons per body mass
Brain['Forebrain n per body m'] = Brain['Forebrain n']/Brain['Body m']
Brain['Cerebellum n per body m'] = Brain['Cerebellum n']/Brain['Body m']
Brain['Whole brain n per body m'] = Brain['Whole brain n']/Brain['Body m']

In [13]:
Breng = Brain
Breng.head()

Animal  Forebrain m  Cerebellum m  Whole brain m  \
0  African sheath-tailed bat       0.0899        0.0540          0.244   
1     Little free-tailed bat       0.0840        0.0360          0.208   
2         Rufous trident bat       0.0930        0.0720          0.251   
3       Common bent-wing bat       0.0858        0.0485          0.219   
4             Naked mole-rat       0.1840        0.0480          0.392   

   Forebrain n  Cerebellum n  Whole brain n  Body m  Forebrain m r %  \
0    5080000.0    47984000.0     58580000.0    11.5        36.844262   
1    5632000.0    25324000.0     34958000.0     5.4        40.384615   
2    6039000.0    59651000.0     69763000.0    13.7        37.051793   
3    6116000.0    44447000.0     55659000.0    11.6        39.178082   
4    6150000.0    15740000.0     26880000.0    35.3        46.938776   

   Cerebellum m r %  Forebrain n r %  Cerebellum n r %  Forebrain n d  \
0         22.131148         8.671902         81.911915   56507.230256   
1         17.307692        16.110761         72.441215   67047.619048   
2         28.685259         8.656451         85.505210   64935.483871   
3         22.146119        10.988340         79.855908   71282.051282   
4         12.244898        22.879464         58.556548   33423.913043   

   Cerebellum n d  Whole brain n d  Forebrain n per body m  \
0   888592.592593    240081.967213            4.417391e+05   
1   703444.444444    168067.307692            1.042963e+06   
2   828486.111111    277940.239044            4.408029e+05   
3   916432.989691    254150.684932            5.272414e+05   
4   327916.666667     68571.428571            1.742210e+05   

   Cerebellum n per body m  Whole brain n per body m  
0             4.172522e+06              5.093913e+06  
1             4.689630e+06              6.473704e+06  
2             4.354088e+06              5.092190e+06  
3             3.831638e+06              4.798190e+06  
4             4.458924e+05              7.614731e+05

In [14]:
Breng.describe()

Forebrain m  Cerebellum m  Whole brain m   Forebrain n  Cerebellum n  \
count    68.000000     68.000000      68.000000  6.800000e+01  6.800000e+01   
mean    100.513246     26.718581     148.837794  7.230677e+08  6.422139e+09   
std     375.463562    142.883307     587.417764  2.108964e+09  3.132655e+10   
min       0.084000      0.020000       0.176000  5.080000e+06  1.574000e+07   
25%       0.594500      0.183000       1.167750  2.247725e+07  1.185145e+08   
50%       9.884000      1.895000      16.291500  2.331350e+08  7.084950e+08   
75%      49.483000      7.725500      79.140500  5.515975e+08  2.293000e+09   
max    2847.000000   1171.000000    4618.000000  1.634000e+10  2.507000e+11   

       Whole brain n        Body m  Forebrain m r %  Cerebellum m r %  \
count   6.800000e+01  6.800000e+01        68.000000         68.000000   
mean    7.227403e+09  1.033938e+05        59.178199         13.425782   
std     3.260552e+10  5.878408e+05        11.443304          4.085992   
min     2.688000e+07  5.400000e+00        36.844262          8.662211   
25%     1.605238e+08  9.892500e+01        50.724418         10.501730   
50%     8.816650e+08  1.566000e+03        59.277233         12.482964   
75%     3.294250e+09  1.977500e+04        67.938807         15.352014   
max     2.570400e+11  4.800000e+06        81.697613         28.685259   

       Forebrain n r %  Cerebellum n r %  Forebrain n d  Cerebellum n d  \
count        68.000000         68.000000      68.000000    6.800000e+01   
mean         18.458402         75.568089   27178.790180    4.480635e+05   
std           7.755877          8.616045   21795.336020    2.365565e+05   
min           2.175926         54.274301    1130.495495    1.272029e+05   
25%          13.060446         71.318788   11719.709289    2.454826e+05   
50%          18.082744         76.147903   22280.533535    4.071960e+05   
75%          22.293038         80.627305   38818.820596    5.936429e+05   
max          44.074567         97.533458  115833.333333    1.043500e+06   

       Whole brain n d  Forebrain n per body m  Cerebellum n per body m  \
count        68.000000            6.800000e+01             6.800000e+01   
mean      84382.794052            2.375565e+05             9.750194e+05   
std       59774.481458            3.081021e+05             1.191874e+06   
min       16004.040931            9.043964e+02             1.109750e+04   
25%       38797.525865            3.949897e+04             1.348416e+05   
50%       69625.125870            1.146389e+05             4.503212e+05   
75%      109916.144278            3.200237e+05             1.448941e+06   
max      277940.239044            1.448649e+06             4.689630e+06   

       Whole brain n per body m  
count              6.800000e+01  
mean               1.320032e+06  
std                1.584400e+06  
min                1.343875e+04  
25%                2.044380e+05  
50%                5.971862e+05  
75%                2.029670e+06  
max                6.473704e+06

In [15]:
Breng.shape

(68, 18)

In [16]:
# pd.set_option('display.max_rows', 170)
# Breng.head(170)

In [17]:
X00 = Breng['Forebrain m']
Y00 = Breng["Forebrain n"]

In [19]:
# The correlation between Forebrain mass and number of neurons
r0 = np.corrcoef(X00, Y00)
r0

array([[1.       , 0.6479588],
       [0.6479588, 1.       ]])

In [20]:
X01 = Breng['Cerebellum m']
Y01 = Breng["Cerebellum n"]

In [21]:
# The same for cerebellum
r1 = np.corrcoef(X01, Y01)
r1

array([[1.        , 0.98975691],
       [0.98975691, 1.        ]])

In [23]:
X02 = Breng['Forebrain m r %']
Y02 = Breng["Forebrain n r %"]

In [24]:
# The correlation between relative cortical mass and relative number of neurons
r2 = np.corrcoef(X02, Y02)
r2

array([[1.        , 0.44039973],
       [0.44039973, 1.        ]])

In [25]:
X03 = Breng['Cerebellum m r %']
Y03 = Breng["Cerebellum n r %"]

In [26]:
# Same as above for cerebellum
r3 = np.corrcoef(X03, Y03)
r3

array([[1.        , 0.49213583],
       [0.49213583, 1.        ]])

In [27]:
Y04 = Breng["Body m"]

In [28]:
# Correlation between body mass and number of neurons in the cortex
r4 = np.corrcoef(Y00, Y04)
r4

array([[1.       , 0.3013604],
       [0.3013604, 1.       ]])

In [29]:
# Saving modified data
Breng.to_csv('/content/mammals with feature engineering 14 07 2023 .csv')