In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [ ]:
Br = pd.read_csv("Brain Data.csv")
Br.head(8)

Animal  Forebr m   Cer m  rest m   Forebr n       Cer n  \
0                        NaN       NaN     NaN     NaN        NaN         NaN   
1  African sheath-tailed bat    0.0899  0.0540   0.098  5,080,000  47,984,000   
2     Little free-tailed bat    0.0840  0.0360   0.084  5,632,000  25,324,000   
3         Rufous trident bat    0.0930  0.0720   0.084  6,039,000  59,651,000   
4       Common bent-wing bat    0.0858  0.0485   0.086  6,116,000  44,447,000   
5             Naked mole-rat    0.1840  0.0480   0.160  6,150,000  15,740,000   
6  Commerson's roundleaf bat    0.2430  0.1070   0.237  7,877,000  51,875,000   
7                Smoky shrew    0.0840  0.0200   0.072  9,730,000  20,870,000   

      Rest n  Body m  
0        NaN     NaN  
1  5,514,000    11.5  
2  4,001,000     5.4  
3  4,072,000    13.7  
4  5,094,000    11.6  
5  4,980,000    35.3  
6  6,965,000   101.9  
7  5,560,000     7.5

In [ ]:
Br = Br.dropna()

In [ ]:
Br.dtypes

Animal       object
Forebr m    float64
Cer m       float64
rest m      float64
Forebr n     object
Cer n        object
Rest n       object
Body m      float64
dtype: object

In [ ]:
Br.head(7)

Animal  Forebr m   Cer m  rest m   Forebr n       Cer n  \
1  African sheath-tailed bat    0.0899  0.0540   0.098  5,080,000  47,984,000   
2     Little free-tailed bat    0.0840  0.0360   0.084  5,632,000  25,324,000   
3         Rufous trident bat    0.0930  0.0720   0.084  6,039,000  59,651,000   
4       Common bent-wing bat    0.0858  0.0485   0.086  6,116,000  44,447,000   
5             Naked mole-rat    0.1840  0.0480   0.160  6,150,000  15,740,000   
6  Commerson's roundleaf bat    0.2430  0.1070   0.237  7,877,000  51,875,000   
7                Smoky shrew    0.0840  0.0200   0.072  9,730,000  20,870,000   

      Rest n  Body m  
1  5,514,000    11.5  
2  4,001,000     5.4  
3  4,072,000    13.7  
4  5,094,000    11.6  
5  4,980,000    35.3  
6  6,965,000   101.9  
7  5,560,000     7.5

In [ ]:
Br['Forebr n'].dtype

dtype('O')

In [ ]:
Br['Cer m'].dtype

dtype('float64')

In [ ]:
if Br['Forebr n'].dtype != 'float64': 
     Br['Forebr n'] = Br['Forebr n'].str.replace(',', '').astype(float)
if Br['Cer n'].dtype != 'float64':
     Br['Cer n'] = Br['Cer n'].str.replace(',', '').astype(float)
if Br['Rest n'].dtype != 'float64':
     Br['Rest n'] = Br['Rest n'].str.replace(',', '').astype(float)

In [ ]:
Br.dtypes

Animal       object
Forebr m    float64
Cer m       float64
rest m      float64
Forebr n    float64
Cer n       float64
Rest n      float64
Body m      float64
dtype: object

In [ ]:
Br.head(5)

Animal  Forebr m   Cer m  rest m   Forebr n       Cer n  \
1  African sheath-tailed bat    0.0899  0.0540   0.098  5080000.0  47984000.0   
2     Little free-tailed bat    0.0840  0.0360   0.084  5632000.0  25324000.0   
3         Rufous trident bat    0.0930  0.0720   0.084  6039000.0  59651000.0   
4       Common bent-wing bat    0.0858  0.0485   0.086  6116000.0  44447000.0   
5             Naked mole-rat    0.1840  0.0480   0.160  6150000.0  15740000.0   

      Rest n  Body m  
1  5514000.0    11.5  
2  4001000.0     5.4  
3  4072000.0    13.7  
4  5094000.0    11.6  
5  4980000.0    35.3

In [ ]:
X = Br[["Forebr m", "Cer m", "rest m", "Body m"]]
Y1 = Br["Forebr n"]
Y2 = Br["Cer n"]
Y3 = Br["Rest n"]

In [ ]:
x_train, x_test, y_train1, y_test1 = train_test_split(X, Y1, test_size=0.25)
x_train

Forebr m     Cer m  rest m    Body m
10      0.197    0.0370   0.113     21.60
22      1.805    0.4560   1.169    310.00
114    14.377    1.2450   5.109   1030.00
115   382.770  106.1400  74.620  52500.00
51      3.600    0.6496   1.105   1361.67
..        ...       ...     ...       ...
3       0.093    0.0720   0.084     13.70
19      0.908    0.3910   0.500     64.80
83     24.491    3.3380   6.357   6000.00
5       0.184    0.0480   0.160     35.30
38      0.277    0.0560   0.161     12.00

[88 rows x 4 columns]

In [ ]:
regr = RandomForestRegressor()

In [ ]:
regr.fit(x_train, y_train1)

RandomForestRegressor()

In [ ]:
regr.predict(x_test)

array([2.0672090e+07, 7.2739052e+08, 8.0739200e+06, 2.9537822e+08,
       6.0982511e+08, 4.6787130e+07, 3.8986496e+08, 1.6439801e+08,
       5.2453890e+07, 1.8435390e+07, 6.2740609e+08, 3.1143463e+08,
       1.1040241e+08, 2.9875360e+07, 9.3883760e+08, 7.1788960e+07,
       2.5102556e+08, 5.6432080e+08, 7.9117562e+08, 1.9397943e+08,
       4.9639900e+07, 1.2256461e+08, 1.4855303e+08, 2.3724010e+07,
       2.9056682e+08, 8.6134972e+08, 4.3819010e+07, 4.4484576e+08,
       4.7804465e+08, 4.3093917e+08])

In [ ]:
mean_squared_error(y_test1, regr.predict(x_test))

9.938392830230995e+16

In [ ]:
r2_score(y_test1, regr.predict(x_test))

0.5219988034942642

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
reg2 = GradientBoostingRegressor(random_state=0)

In [ ]:
reg2.fit(x_train, y_train1)

GradientBoostingRegressor(random_state=0)

In [ ]:
reg2.predict(x_test)

array([2.43191435e+07, 7.73485433e+08, 1.71788769e+07, 3.59714210e+08,
       6.83481672e+08, 4.90099529e+07, 2.44577386e+08, 1.72595269e+08,
       4.12578255e+07, 2.32583075e+07, 4.71488435e+08, 2.89660451e+08,
       1.36981241e+08, 3.51349582e+07, 6.25048229e+08, 7.42069625e+07,
       3.25517068e+08, 7.00704880e+08, 7.62244933e+08, 3.16682769e+08,
       4.12578255e+07, 9.55822036e+07, 1.66933198e+08, 2.65205630e+07,
       3.46446957e+08, 7.61425752e+08, 5.07725674e+07, 5.79287614e+08,
       4.66270405e+08, 3.73066146e+08])

In [ ]:
mean_squared_error(y_test1, reg2.predict(x_test))

9.078122473862864e+16

In [ ]:
r2_score(y_test1, reg2.predict(x_test))

0.5633747348633229

In [ ]:
reg2.score(x_test, y_test1)

0.5633747348633229

In [ ]:
reg2.predict([[1200, 150, 120, 70000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([1.63061789e+10])

In [ ]:
reg2.predict([[5270, 753, 192, 3987500]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([8.80159868e+09])

In [ ]:
reg2.predict([[2383, 575, 205, 100000000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([1.03410211e+10])

In [ ]:
reg2.predict([[414, 35, 40, 64475]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([2.53984956e+09])

In [ ]:
reg2.predict([[2431, 403, 91, 2200000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([1.05598494e+10])

In [ ]:
reg2.predict([[1519, 301, 90, 200000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([1.37043018e+10])

In [ ]:
reg2.predict([[7466, 550, 184, 28500000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([1.03410211e+10])

In [ ]:
x_test

Forebr m    Cer m   rest m     Body m
21      0.360   0.1090   0.2600      94.86
68     24.176   5.1100   5.5720    3900.00
42      0.176   0.0400   0.1410       5.60
59      2.260   0.4028   0.8545     649.30
105     6.490   0.6228   1.3180     549.67
20      1.040   0.2860   0.7120     120.00
93     12.540   2.3578   3.1130    5228.20
70      1.368   0.1960   0.6420      90.00
39      0.820   0.2376   0.5430     388.70
6       0.243   0.1070   0.2370     101.90
97      5.502   0.5710   2.2020     275.00
92      2.854   0.4110   1.3310     159.70
33      1.938   0.5000   1.2180     728.00
44      0.915   0.3320   0.8480     358.70
94    139.902  24.8820  34.1620  175000.00
61      0.775   0.1440   0.3970      30.00
45      2.730   0.8740   1.9430     533.00
107    13.480   1.2854   2.1630    1770.00
111    48.274   5.7480   7.4480    6755.00
66      1.880   0.5032   0.8350     204.33
34      0.880   0.2526   0.5420     475.75
55      3.150   0.8543   1.5970    3599.20
58      1.091   0.2130   0.5840     103.20
14      0.429   0.1020   0.2280      62.50
56      2.040   0.4330   0.7300     452.20
104    39.178   4.6000   8.4300    2643.00
47      0.580   0.0900   0.2700      17.90
109    11.720   1.2078   2.0810    2342.33
89      4.165   0.4830   1.3760     246.00
96      3.657   0.5060   1.5370     255.00