In [144]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.linear_model import Ridge

In [145]:
Br = pd.read_csv("Brain Data.csv")
Br.head(8)

Animal  Forebr m   Cer m  rest m   Forebr n       Cer n  \
0                        NaN       NaN     NaN     NaN        NaN         NaN   
1  African sheath-tailed bat    0.0899  0.0540   0.098  5,080,000  47,984,000   
2     Little free-tailed bat    0.0840  0.0360   0.084  5,632,000  25,324,000   
3         Rufous trident bat    0.0930  0.0720   0.084  6,039,000  59,651,000   
4       Common bent-wing bat    0.0858  0.0485   0.086  6,116,000  44,447,000   
5             Naked mole-rat    0.1840  0.0480   0.160  6,150,000  15,740,000   
6  Commerson's roundleaf bat    0.2430  0.1070   0.237  7,877,000  51,875,000   
7                Smoky shrew    0.0840  0.0200   0.072  9,730,000  20,870,000   

      Rest n  Body m  
0        NaN     NaN  
1  5,514,000    11.5  
2  4,001,000     5.4  
3  4,072,000    13.7  
4  5,094,000    11.6  
5  4,980,000    35.3  
6  6,965,000   101.9  
7  5,560,000     7.5

In [146]:
Br = Br.dropna()

In [147]:
Br.dtypes

Animal       object
Forebr m    float64
Cer m       float64
rest m      float64
Forebr n     object
Cer n        object
Rest n       object
Body m      float64
dtype: object

In [148]:
Br.head(7)

Animal  Forebr m   Cer m  rest m   Forebr n       Cer n  \
1  African sheath-tailed bat    0.0899  0.0540   0.098  5,080,000  47,984,000   
2     Little free-tailed bat    0.0840  0.0360   0.084  5,632,000  25,324,000   
3         Rufous trident bat    0.0930  0.0720   0.084  6,039,000  59,651,000   
4       Common bent-wing bat    0.0858  0.0485   0.086  6,116,000  44,447,000   
5             Naked mole-rat    0.1840  0.0480   0.160  6,150,000  15,740,000   
6  Commerson's roundleaf bat    0.2430  0.1070   0.237  7,877,000  51,875,000   
7                Smoky shrew    0.0840  0.0200   0.072  9,730,000  20,870,000   

      Rest n  Body m  
1  5,514,000    11.5  
2  4,001,000     5.4  
3  4,072,000    13.7  
4  5,094,000    11.6  
5  4,980,000    35.3  
6  6,965,000   101.9  
7  5,560,000     7.5

In [149]:
Br['Forebr n'].dtype

dtype('O')

In [150]:
Br['Cer m'].dtype

dtype('float64')

In [151]:
if Br['Forebr n'].dtype != 'float64': 
     Br['Forebr n'] = Br['Forebr n'].str.replace(',', '').astype(float)
if Br['Cer n'].dtype != 'float64':
     Br['Cer n'] = Br['Cer n'].str.replace(',', '').astype(float)
if Br['Rest n'].dtype != 'float64':
     Br['Rest n'] = Br['Rest n'].str.replace(',', '').astype(float)

In [152]:
Br.dtypes

Animal       object
Forebr m    float64
Cer m       float64
rest m      float64
Forebr n    float64
Cer n       float64
Rest n      float64
Body m      float64
dtype: object

In [153]:
Br.head(5)

Animal  Forebr m   Cer m  rest m   Forebr n       Cer n  \
1  African sheath-tailed bat    0.0899  0.0540   0.098  5080000.0  47984000.0   
2     Little free-tailed bat    0.0840  0.0360   0.084  5632000.0  25324000.0   
3         Rufous trident bat    0.0930  0.0720   0.084  6039000.0  59651000.0   
4       Common bent-wing bat    0.0858  0.0485   0.086  6116000.0  44447000.0   
5             Naked mole-rat    0.1840  0.0480   0.160  6150000.0  15740000.0   

      Rest n  Body m  
1  5514000.0    11.5  
2  4001000.0     5.4  
3  4072000.0    13.7  
4  5094000.0    11.6  
5  4980000.0    35.3

In [154]:
X = Br[["Forebr m", "Cer m", "rest m", "Body m"]]
Y1 = Br["Forebr n"]
Y2 = Br["Cer n"]
Y3 = Br["Rest n"]

Predicting for Cerebral Cortex

In [271]:
x_train, x_test, y_train1, y_test1 = train_test_split(X, Y1, test_size=0.25)
x_train

Forebr m     Cer m  rest m     Body m
55      3.150    0.8543   1.597    3599.20
56      2.040    0.4330   0.730     452.20
115   382.770  106.1400  74.620   52500.00
6       0.243    0.1070   0.237     101.90
100    36.226    5.6420   4.294    6363.00
..        ...       ...     ...        ...
20      1.040    0.2860   0.712     120.00
21      0.360    0.1090   0.260      94.86
2       0.084    0.0360   0.084       5.40
98      3.840    0.4746   0.854     248.06
99    213.370   31.7760  61.716  217500.00

[88 rows x 4 columns]

In [272]:
y_train1

55     1.296210e+08
56     1.301420e+08
115    2.770000e+09
6      7.877000e+06
100    8.009600e+08
           ...     
20     2.253300e+07
21     2.256800e+07
2      5.632000e+06
98     6.730000e+08
99     7.620000e+08
Name: Forebr n, Length: 88, dtype: float64

In [273]:
x_test

Forebr m    Cer m  rest m    Body m
66     1.8800   0.5032   0.835    204.33
91    65.4910   7.5120  13.459  40000.00
92     2.8540   0.4110   1.331    159.70
50     2.8900   0.8564   1.802   3453.33
9      0.4610   0.1270   0.301     27.00
40     1.3350   0.3690   1.115    779.80
3      0.0930   0.0720   0.084     13.70
47     0.5800   0.0900   0.270     17.90
34     0.8800   0.2526   0.542    475.75
68    24.1760   5.1100   5.572   3900.00
81     2.9900   0.3585   0.668    169.56
35     1.2800   0.4016   0.781    468.33
4      0.0858   0.0485   0.086     11.60
80     5.9300   1.3985   1.749   1747.00
37     0.4540   0.0840   0.236     16.70
39     0.8200   0.2376   0.543    388.70
14     0.4290   0.1020   0.228     62.50
23     0.9240   0.3300   0.824    356.50
63    10.4780   2.0580   4.317   3600.00
33     1.9380   0.5000   1.218    728.00
44     0.9150   0.3320   0.848    358.70
17     0.2400   0.0776   0.180     39.93
93    12.5400   2.3578   3.113   5228.20
18     0.2200   0.0717   0.178     43.81
57     0.8600   0.2106   0.431     63.91
112   69.8320   7.6940   9.204   8235.00
101    5.7690   0.6570   1.931    453.50
82     3.8520   0.5100   1.255    580.00
89     4.1650   0.4830   1.376    246.00
116  120.2140  13.7450  17.235  20000.00

In [300]:
regr1 = Ridge(alpha=0.1)

In [301]:
regr1.fit(x_train, y_train1)

Ridge(alpha=0.1)

In [302]:
regr1.predict(x_test)

array([2.96689027e+08, 7.44261078e+08, 2.93769516e+08, 2.61517917e+08,
       2.97257557e+08, 2.74052798e+08, 3.00391956e+08, 3.01062572e+08,
       2.92267951e+08, 4.52850990e+08, 3.25270875e+08, 2.88124582e+08,
       3.00354892e+08, 3.19863033e+08, 3.00288722e+08, 2.91488841e+08,
       2.99917825e+08, 2.80635386e+08, 2.81463128e+08, 2.79739952e+08,
       2.79413002e+08, 2.98799919e+08, 3.64233382e+08, 2.98555541e+08,
       2.98170006e+08, 1.09490535e+09, 3.18197973e+08, 3.13294343e+08,
       3.14892866e+08, 1.58614969e+09])

In [303]:
mean_squared_error(y_test1, regr1.predict(x_test))

1.1893598357556846e+17

In [304]:
mean_squared_error(y_train1, regr1.predict(x_train))

1.5181149040713782e+17

In [305]:
r2_score(y_test1, regr1.predict(x_test))

0.650110017114996

In [306]:
# Human(included in data)
regr1.predict([[1200, 150, 120, 70000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([1.56311736e+10])

In [307]:
# Killer whale
regr1.predict([[5270, 753, 192, 3987500]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([7.10850045e+10])

In [308]:
# Bowhead whale
regr1.predict([[2383, 575, 205, 100000000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([-2.49883399e+11])

In [309]:
# Orangutan
regr1.predict([[414, 35, 40, 64475]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([5.66298057e+09])

In [310]:
# Short finned pilot whale
regr1.predict([[2431, 403, 91, 2200000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([3.14245449e+10])

In [311]:
# Bottlenose dolphin
regr1.predict([[1519, 301, 90, 200000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([2.12448511e+10])

In [312]:
# Sperm whale
regr1.predict([[7466, 550, 184, 28500000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([4.41482424e+10])

In [313]:
# Beluga whale
regr1.predict([[1830, 301, 69, 1430000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([2.43606381e+10])

Predicting for cerebellum

In [72]:
x_train, x_test, y_train2, y_test2 = train_test_split(X, Y2, test_size=0.25)

In [73]:
regr2 = Ridge(alpha=0.1)

In [75]:
regr2.fit(x_train, y_train2)

Ridge(alpha=0.1)

In [76]:
regr2.predict(x_test)

array([4.89389883e+08, 4.12609958e+08, 3.97815787e+08, 1.23889959e+09,
       2.94439884e+08, 3.01201704e+08, 1.60441910e+09, 3.38407798e+08,
       2.99112490e+08, 2.94573165e+08, 3.00907057e+08, 4.61206711e+08,
       3.05422625e+08, 3.50346052e+08, 2.89262939e+08, 3.31664098e+08,
       2.94395462e+08, 3.51010947e+08, 3.05566845e+08, 2.91314376e+09,
       3.02941191e+08, 1.71760200e+09, 2.89225583e+08, 3.35629526e+08,
       5.95061339e+08, 4.61909855e+10, 5.91232202e+08, 4.48844442e+08,
       2.91181644e+08, 2.93701132e+08])

In [77]:
mean_squared_error(y_test2, regr2.predict(x_test))

1.7478731917729896e+19

In [78]:
mean_squared_error(y_train2, regr2.predict(x_train))

3.961264915209984e+17

In [79]:
r2_score(y_test2, regr2.predict(x_test))

0.88473014114047

In [80]:
# Human(included in data)
regr2.predict([[1200, 150, 120, 70000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([4.44309922e+10])

In [81]:
# Killer whale
regr2.predict([[5270, 753, 192, 3987500]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([2.18564749e+11])

In [82]:
# Bowhead whale
regr2.predict([[2383, 575, 205, 100000000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([-6.47773765e+11])

In [83]:
# Orangutan
regr2.predict([[414, 35, 40, 64475]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([1.10347379e+10])

In [84]:
# Short finned pilot whale
regr2.predict([[2431, 403, 91, 2200000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([1.12045133e+11])

In [85]:
# Bottlenose dolphin
regr2.predict([[1519, 301, 90, 200000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([8.92189571e+10])

In [86]:
# Sperm whale
regr2.predict([[7466, 550, 184, 28500000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([2.17474402e+08])

In [87]:
# Beluga whale
regr2.predict([[1830, 301, 69, 1430000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([8.55978819e+10])

Predicting for rest of the brain

In [129]:
x_train, x_test, y_train3, y_test3 = train_test_split(X, Y3, test_size=0.25)

In [130]:
regr3 = Ridge(alpha=0.1)

In [131]:
regr3.fit(x_train, y_train3)

Ridge(alpha=0.1)

In [132]:
regr3.predict(x_test)

array([4.90205202e+08, 5.90595149e+07, 5.96935328e+07, 5.78015463e+07,
       6.15780426e+07, 5.78914651e+07, 5.99310751e+07, 5.99557023e+07,
       5.74230811e+07, 5.76110941e+07, 6.10437449e+07, 5.79140508e+07,
       6.21160724e+07, 5.92167188e+07, 7.53311136e+07, 5.74286423e+07,
       5.75234096e+07, 5.92820288e+07, 5.74679000e+07, 5.77705100e+07,
       5.78196676e+07, 6.24583547e+07, 5.86996323e+07, 5.75759783e+07,
       8.25978312e+07, 5.76825844e+07, 8.72334159e+07, 5.82039799e+07,
       5.88028043e+07, 5.73680191e+07])

In [133]:
mean_squared_error(y_test3, regr3.predict(x_test))

2486141373632344.0

In [134]:
mean_squared_error(y_train3, regr3.predict(x_train))

8405207319805521.0

In [135]:
r2_score(y_test3, regr3.predict(x_test))

0.8269504526509168

In [136]:
# Human(included in data)
regr3.predict([[1200, 150, 120, 70000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([4.80766816e+08])

In [137]:
# Killer whale
regr3.predict([[5270, 753, 192, 3987500]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([1.52744087e+09])

In [138]:
# Bowhead whale
regr3.predict([[2383, 575, 205, 100000000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([-5.18682217e+09])

In [139]:
# Orangutan
regr3.predict([[414, 35, 40, 64475]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([2.03942706e+08])

In [140]:
# Short finned pilot whale
regr3.predict([[2431, 403, 91, 2200000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([7.02937919e+08])

In [141]:
# Bottlenose dolphin
regr3.predict([[1519, 301, 90, 200000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([5.35546757e+08])

In [142]:
# Sperm whale
regr3.predict([[7466, 550, 184, 28500000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([8.36198721e+08])

In [143]:
# Beluga whale
regr3.predict([[1830, 301, 69, 1430000]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([5.57661572e+08])